# Generated by Django 5.2.8 on 2025-12-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_status_alter_article_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="approved",
        ),
    ]
