# Generated by Django 5.2.8 on 2025-12-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_remove_article_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="moderation_comment",
            field=models.TextField(
                blank=True, help_text="Reason for rejection", null=True
            ),
        ),
    ]
