# Generated by Django 5.2.8 on 2025-12-16 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_moderationlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moderationlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="moderationlog",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="moderationlog",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_logs",
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="moderationlog",
            name="moderator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderation_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
